"use client";
import "./globals.css";
import type { Metadata } from "next";
import Header from "./components/Header";
import { ThemeProvider, createTheme } from "@mui/material/styles";

const lightTheme = createTheme({
  palette: {
    mode: "light",
  },
});

export const metadata: Metadata = {
  title: "CuriousCourses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ background: "white", color: "black" }}>
        <ThemeProvider theme={lightTheme}>
          <Header />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
